In [ ]:
#import tensorflow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
#creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the no of dimensions(ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
#create a vector
vector = tf.constant([0,89])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 0, 89], dtype=int32)>

In [ ]:
vector.ndim
# vector = tf.constant([[[[0,89]]]]) dimension = 4

1

In [ ]:
#create a matrix(has more than 1 dimension)
matrix = tf.constant([[19],[2]])
matrix


<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[19],
       [ 2]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[19,23.12,1],[23,12,3],[12,42,123]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[ 19.  ,  23.12,   1.  ],
       [ 23.  ,  12.  ,   3.  ],
       [ 12.  ,  42.  , 123.  ]], dtype=float16)>

In [ ]:
another_matrix.ndim #so basic dimension refer to how many numbers are in shape

2

In [ ]:
#create tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim


3

## scalar: a single number
## vector: a number with disable_graph_collection
## matrix: a 2-dimensional array of numbers
## tensor: an n-dimensional array of numbers

A tf.Tensor is a data structure that represents a value in a TensorFlow graph. It is immutable, meaning that its value cannot be changed once it is created. A tf.Variable is a special type of tf.Tensor that can be modified during training.

In eager execution, tf.Tensors and tf.Variables are created automatically when you use operations like tf.add and tf.assign. In graph execution, you must explicitly create tf.Tensors and tf.Variables using operations like tf.placeholder and tf.get_variable.

Eager execution is more convenient and easier to use than graph execution. However, graph execution is more efficient and can be used to train models on large datasets.

 | Feature | Eager tensor | Resource variable |
|---|---|---|
| Mutability | Immutable | Mutable |
| Creation | Automatic | Explicit |
| Execution | Eager | Graph |
| Efficiency | Less efficient | More efficient |
| Convenience | More convenient | Less convenient |

In [ ]:
#creating tensors with tf.Variable
changeable_tensor = tf.Variable([10,7])      #eager tensor
unchangeable_tensor = tf.constant([10,7])    #resource variable

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#changing elements in variable or changeable tensor
# changeable_tensor[0] = 7
# changeable_tensor

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

In [ ]:
#creating random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2
# created two random tensor with same seed

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [ ]:
random_1 == random_2
# it means that although they seem to appear random they are same because of the same seed value
# this helps in reproducibility of results

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

# shuffling tensor so the same order of values doesn't affect learning

In [ ]:
not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5],
                            [0,2],
                            [89,96]])

not_shuffled


<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5],
       [ 0,  2],
       [89, 96]], dtype=int32)>

In [ ]:
not_shuffled.ndim

2

In [ ]:
tf.random.shuffle(not_shuffled)
#random shuffled a tensor alog with its firs dimension only

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [ 0,  2],
       [10,  7],
       [89, 96]], dtype=int32)>

In [ ]:
# tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [ 0,  2],
       [89, 96],
       [10,  7]], dtype=int32)>

In [ ]:
tf.ones([10,3])

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([8,3])

<tf.Tensor: shape=(8, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

# turn numpy arrays in tensors

In [ ]:
#tensors run faster on gpu than numpy otherwise they are same
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
tensor_A = tf.constant(numpy_A)
tensor_A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
tensor_B = tf.Variable(numpy_A)
tensor_B

<tf.Variable 'Variable:0' shape=(24,) dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
A = tf.constant(numpy_A,shape = (3,8))
B = tf.constant(numpy_A)
# we can change the size of tensor with shape but shape values must evaluate to be same as total elements
# eg: 24 elements in numpy_A, shape could be (2,3,4)(3,8)(8,3) etc.
A,B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
A.ndim , B.ndim

(2, 1)

#getting information from tensors
shape

rank

axis or dimension

size

In [ ]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.ndim

4

In [ ]:
rank_4_tensor.shape,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
rank_4_tensor[0].shape,tf.size(rank_4_tensor[0])

(TensorShape([3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=60>)

In [ ]:
#get various attributes of tensor
print("Datatype of every element:",rank_4_tensor.dtype)
print("Number of dimensions (rank):",rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("Elements along the 0 axis:",rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in tensor:",tf.size(rank_4_tensor))
print("Total number of elements in tensor:",tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in tensor: 120


In [ ]:
###indexing tensors

In [ ]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1,:2,:1,:]

<tf.Tensor: shape=(1, 2, 1, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]]]], dtype=float32)>